{% set name = "molflux" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/molflux-{{ version }}.tar.gz
  sha256: 54edae23fbb8f7ee2c19ed6f4197ad2e54df96c126a9072aa8e64a7322e4a719

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64.0.0
    - setuptools-scm >=6.2.0
    - pip
  run:
    - typing_extensions
    - python >={{ python_min }},<3.12
    - boto3 >=1.34.0
    - botocore >=1.28.16
    - cloudpathlib
    - colorama
    - datasets >=2.17.0
    - evaluate
    - fsspec >=2022.5.0
    - h5py
    - joblib
    - mergedeep
    - more-itertools
    - numpy <2.0.0
    - pandas
    - pyarrow >=11.0.0
    - pydantic >=1.10.15,<3
    - python-dateutil
    - pyyaml
    - qlient
    - requests
    - scikit-learn >=1.4.0
    - scipy >=1.7.0
    - tenacity
    - thefuzz
    - tqdm
    - typing-extensions
    - urllib3 <2.1,>=1.25.4

test:
  imports:
    - molflux
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: A foundational package for molecular predictive modelling
  home: https://github.com/Exscientia/molflux
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
