{% set name = "molflux" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/molflux-{{ version }}.tar.gz
  sha256: 7076a225f795945df0d652e18d7ffc9521945eb58ebffff998edd5389c181bfa

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<3.12
    - setuptools >=64.0.0
    - setuptools-scm >=6.2.0
    - pip
  run:
    - python >=3.8,<3.12
    - boto3 >=1.28.16
    - botocore >=1.28.16
    - cloudpathlib
    - colorama
    - datasets >=2.17.0
    - evaluate
    - fsspec >=2022.5.0
    - h5py
    - joblib
    - mergedeep
    - more-itertools
    - numpy <2.0.0
    - pandas
    - pyarrow >=11.0.0
    - pydantic >=1.10.15,<3
    - python-dateutil
    - pyyaml
    - qlient
    - requests
    - scikit-learn >=1.4.0
    - scipy >=1.7.0
    - tenacity
    - thefuzz
    - tqdm
    - typing-extensions
    - urllib3 <2.1,>=1.25.4

test:
  imports:
    - molflux
  commands:
    - pip check
  requires:
    - pip

about:
  summary: A foundational package for molecular predictive modelling
  home: https://github.com/Exscientia/molflux
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
